In [1]:
import matplotlib
import matplotlib.pyplot as plt
#from labellines import labelLine, labelLines
import seaborn as sns
import os
import pandas as pd
import glob
import numpy as np

In [2]:
path = '/uscms/home/jieun201/nobackup/YOURWORKINGAREA/june23_ds8_labelsOnly'
csv_files = glob.glob(path + "/*.csv")
df_labels = (pd.read_csv(file) for file in csv_files)
big_df_labels   = pd.concat(df_labels, ignore_index=True)

In [3]:
big_df_labels

x-entry    y-entry  z-entry       n_x       n_y       n_z  \
0         12.063666  30.923424    100.0  0.768970 -0.160933 -0.634940   
1         67.455246   4.533963    100.0 -1.205132 -0.087774 -0.635886   
2       -225.239441  13.836857    100.0  1.451834 -0.039285 -0.467361   
3         -2.914946  11.285143    100.0 -0.110369 -0.034764 -0.554253   
4        286.367920  -9.845788    100.0 -3.201757 -0.015797 -0.738721   
...             ...        ...      ...       ...       ...       ...   
4054839  -79.113602   7.351277    100.0  0.146580 -0.038023 -0.205342   
4054840   83.020744  13.864967    100.0 -0.943910  0.025917 -0.367944   
4054841  -47.450962  26.444847    100.0 -0.148263 -0.086394 -0.386804   
4054842 -212.548859 -10.588823    100.0  1.341313  0.009282 -0.394129   
4054843 -296.235229  -6.661979    100.0  1.546676  0.029554 -0.324567   

         number_eh_pairs  y-local        pt  cotAlpha   cotBeta  y-midplane  \
0                10034.0 -6.94104  0.656019 -1.211091  0.253462   18.250337   
1                15383.0 -4.33669  0.637776  1.895201  0.138034   -2.367746   
2                26680.0 -2.67448  0.468860 -3.106451  0.084057    9.634003   
3                 8183.0 -2.11685  0.555289  0.199131  0.062722    8.149030   
4                27677.0 -0.96378  0.740845  4.334190  0.021384  -10.915001   
...                  ...      ...       ...       ...       ...         ...   
4054839           7226.0 -3.13432  0.209310 -0.713834  0.185169   -1.907180   
4054840          27249.0  5.03778  0.369755  2.565363 -0.070437   17.386834   
4054841           9051.0 -5.19666  0.395818  0.383303  0.223353   15.277176   
4054842          26483.0  1.97901  0.398485 -3.403233 -0.023551   -9.411290   
4054843          44416.0  4.48073  0.326700 -4.765352 -0.091057   -2.109144   

         x-midplane  
0         72.618207  
1        -27.304821  
2        -69.916896  
3        -12.871500  
4         69.658432  
...             ...  
4054839  -43.421927  
4054840  -45.247416  
4054841  -66.616095  
4054842  -42.387186  
4054843  -57.967629  

[4054844 rows x 13 columns]

In [4]:
#path = '/uscms/home/jieun201/nobackup/YOURWORKINGAREA/june23_ds8_negativeLabelsOnly'
#csv_files2 = glob.glob(path + "/*.csv")
#df_labels2 = (pd.read_csv(file) for file in csv_files2)
#big_df_labels2   = pd.concat(df_labels2, ignore_index=True)
#big_df_labels2

In [5]:
#mergePosNeg = pd.concat([big_df_labels, big_df_labels2])
#mergePosNeg

In [6]:
#plt.hist(mergePosNeg['pt'],bins=np.linspace(-5,5,50),histtype='stepfilled');
#plt.xlabel(r'$p_T$ [GeV]')
#plt.ylabel('Tracks')

In [7]:
#nearZeroPT = mergePosNeg[   (mergePosNeg['pt'] > 0) & (mergePosNeg['pt'] < 0.1)]
#nearZeroPT2 = mergePosNeg[   (mergePosNeg['pt'] > -0.1) & (mergePosNeg['pt'] < 0)]

s = pd.Series(big_df_labels['pt'])
BigSampleValueCounts = s.value_counts(bins=[0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1.0,1.1,1.2,1.3,1.4,
                                              1.5,1.6,1.7,1.8,1.9,2.0,10]).sort_index()


In [8]:
TruthTotalCounts = np.array(BigSampleValueCounts)
np.sum(TruthTotalCounts)

#printed out below and saved so the early cells don't need to be run

#TruthTotalCounts

4054844

In [9]:
TruthTotalCounts

array([   380, 216509, 623085, 592413, 505111, 408333, 326467, 259269,
       200540, 166169, 131131, 105435,  85022,  69922,  57426,  47443,
        39366,  32326,  27757,  22776, 137964])

In [10]:
#df1 = pd.read_csv('/uscms/home/jieun201/nobackup/YOURWORKINGAREA/dec6_ds8/TestSetTruePT.csv')
df1 = pd.read_csv('/uscms/home/jieun201/nobackup/YOURWORKINGAREA/shruti2/TestSetTruePT.csv')
df2 = pd.read_csv('predictionsFiles.csv')
df3 = pd.read_csv('true.csv')
df2.columns.values[0] = "predict"
df3.columns.values[0] = "true"
df2['predict'] = df2['predict'].astype(int)
concatenate = pd.concat([df1,df2, df3], axis=1)
#concatenate

In [11]:
s2 = pd.Series(concatenate['pt'])
BigSampleValueCounts2 = s2.value_counts(bins=[0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1.0,1.1,1.2,1.3,1.4,
                                              1.5,1.6,1.7,1.8,1.9,2.0,10]).sort_index()
testSetTotalCounts = np.array(BigSampleValueCounts2)
testSetTotalCounts

array([   82, 40678,  6706,  6404,  5383,  4182,  3395,  2762,  2133,
        1759,  1396,  1123,   906,   781,   610,   495,   442,   349,
         303,   254,  1377])

In [12]:
concatPosPredictRight1 = concatenate[(concatenate['predict'] ==1) | (concatenate['predict'] ==2)]
concatPosPredictRight1

pt  predict  true
0      0.186930        1     1
3      0.516073        1     0
4      0.353187        1     0
5      0.199539        1     1
7      0.159515        1     1
...         ...      ...   ...
81511  0.159317        1     1
81512  0.197112        1     1
81513  0.176577        1     1
81515  0.144134        1     1
81518  0.191594        1     1

[39307 rows x 3 columns]

In [13]:
s3 = pd.Series(concatPosPredictRight1['pt'])
BigSampleValueCounts3 = s3.value_counts(bins=[0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1.0,1.1,1.2,1.3,1.4,
                                              1.5,1.6,1.7,1.8,1.9,2.0,10]).sort_index()
testSetAs12 = np.array(BigSampleValueCounts3)
testSetAs12

array([   80, 29794,  3268,  2049,  1209,   782,   502,   375,   265,
         185,   158,   121,    98,    85,    49,    45,    36,    38,
          25,    29,   114])

In [14]:
makeRatio = TruthTotalCounts/testSetTotalCounts
makeRatio

array([  4.63414634,   5.32250848,  92.91455413,  92.50671455,
        93.83447892,  97.64060258,  96.16111929,  93.87002172,
        94.01781528,  94.46787948,  93.93338109,  93.88691006,
        93.84326711,  89.52880922,  94.14098361,  95.84444444,
        89.06334842,  92.62464183,  91.60726073,  89.66929134,
       100.19172113])

In [15]:
Sum = np.dot(testSetAs12,makeRatio)
Sum

1042779.5770242644

In [16]:
totalTracksTruthSet = 4054844
Sum/totalTracksTruthSet

0.2571688521245859